version: '3.1'

services:
  db:
    container_name: database
    image: sameersbn/postgresql:10-2
    restart: always
    ports:
      - "5432:5432"
    env_file:
      - "app/.env"

  flask:
    container_name: api
    build:
        context: ./app
    command: python main.py
    restart: always
    ports:
      - "5000:80"
    env_file:
      - "app/.env"
