version: '3.1'

services:
  db:
    container_name: database
    image: sameersbn/postgresql:14
    restart: always
    ports:
      - "5432:5432"

  flask:
    container_name: api
    build: ./app
    command: python main/py
    restart: always
    network_mode: "host"
